project:
  status: active
  name: jmolivas/gatsby-theme-novela-example
  buildStatus: ready
  external: false
  provider: github
  deployment:
    buildCommand: gatsby build
    builds:
      master:
        weight: 1
        id: _565yqemzi
        environmentVariables: []
        branch: master
    developmentCommand: gatsby develop
    productionBranch: master
    publishDirectory: public
    packager: npm
    contentDirectory:
      - assets
      - content/authors
      - content/posts
  type: gatsby
schemas:
  - definitions:
      schema:
        id: page
        name: Page
      fields:
        - orderable: true
          removable: true
          system: false
          widget: text
          name: Title
          type: string
          required: true
          value: ''
          id: title
        - value: ''
          id: excerpt
          orderable: true
          removable: true
          system: false
          widget: textarea
          name: Excerpt
          type: string
          required: true
        - value: ''
          id: content
          orderable: true
          removable: true
          system: false
          widget: SlateEditor
          name: Content
          type: string
          required: true
        - system: false
          widget: DatePicker
          name: Date
          type: string
          required: true
          value: ''
          id: date
          orderable: true
          removable: true
        - orderable: true
          removable: true
          system: false
          widget: text
          name: Author
          type: string
          required: true
          value: ''
          id: author
        - name: Hero
          type: string
          required: true
          value: ''
          id: hero
          orderable: true
          removable: true
          system: false
          widget: MediaSchema
    schema:
      json:
        properties:
          author:
            default: ''
            type: string
            title: Author
          excerpt:
            default: ''
            type: string
            title: Excerpt
          hero:
            title: Hero
            default: ''
            type: string
          content:
            title: Content
            default: ''
            type: string
          date:
            default: ''
            type: string
            title: Date
          title:
            default: ''
            type: string
            title: Title
        required:
          - title
          - excerpt
          - content
          - date
          - author
          - hero
        type: object
      name: Page
      ui:
        author:
          'ui:widget': text
        excerpt:
          'ui:widget': textarea
        hero:
          'ui:widget': MediaSchema
        'ui:order':
          - title
          - excerpt
          - content
          - date
          - author
          - hero
          - '*'
        content:
          'ui:widget': SlateEditor
        date:
          'ui:widget': DatePicker
        title:
          'ui:widget': text
    type: content
  - definitions:
      schema:
        name: Authors
        id: authors
      fields:
        - orderable: true
          removable: true
          system: false
          widget: text
          name: Name
          type: string
          required: true
          value: ''
          id: name
        - orderable: true
          removable: true
          system: false
          widget: MediaSchema
          name: Avatar
          type: string
          required: true
          value: ''
          id: avatar
        - system: false
          widget: textarea
          name: Bio
          type: string
          required: true
          value: ''
          id: bio
          orderable: true
          removable: true
        - orderable: true
          removable: true
          system: false
          widget: checkbox
          name: Featured
          type: boolean
          required: false
          value: ''
          id: featured
    schema:
      json:
        properties:
          avatar:
            default: ''
            type: string
            title: Avatar
          featured:
            default: ''
            type: boolean
            title: Featured
          name:
            title: Name
            default: ''
            type: string
          bio:
            title: Bio
            default: ''
            type: string
        required:
          - name
          - avatar
          - bio
        type: object
      name: Authors
      ui:
        name:
          'ui:widget': text
        'ui:order':
          - name
          - avatar
          - bio
          - featured
          - '*'
        bio:
          'ui:widget': textarea
        avatar:
          'ui:widget': MediaSchema
        featured:
          'ui:widget': checkbox
    type: dataset
mapping:
  content:
    - schema: page
      path: content/posts/2017-04-28-understanding-the-gatsby-lifecycle/index.mdx
    - schema: page
      path: content/posts/2018-04-26-how-figma-changed-how-we-design/index.mdx
    - schema: page
      path: content/posts/2017-04-30-how-figma-changed-how-we-design/index.mdx
    - schema: page
      path: content/posts/2017-04-27-building-hoppers-media-centre/index.mdx
    - schema: page
      path: content/posts/2018-04-29-understanding-the-gatsby-lifecycle/index.mdx
    - schema: page
      path: content/posts/2018-04-27-how-figma-changed-how-we-design/index.mdx
    - schema: page
      path: content/posts/2018-04-28-building-hoppers-media-centre/index.mdx
    - schema: page
      path: content/posts/2019-04-26-building-hoppers-media-centre/index.mdx
    - schema: page
      path: content/posts/2019-04-31-understanding-the-gatsby-lifecycle/index.mdx
    - schema: page
      path: content/posts/2018-04-31-building-the-new-hopper-com/index.mdx
    - schema: page
      path: content/posts/2017-04-31-how-figma-changed-how-we-design/index.mdx
    - schema: page
      path: >-
        content/posts/2017-04-30-why-we-built-a-company-before-a-product/index.mdx
    - schema: page
      path: content/posts/2019-04-28-how-figma-changed-how-we-design/index.mdx
    - schema: page
      path: content/posts/2019-04-27-how-figma-changed-how-we-design/index.mdx
    - schema: page
      path: >-
        content/posts/2018-04-30-why-we-built-a-company-before-a-product/index.mdx
    - schema: page
      path: content/posts/2019-04-29-building-the-new-hopper-com/index.mdx
    - schema: page
      path: >-
        content/posts/2019-04-30-why-we-built-a-company-before-a-product/index.mdx
  dataset:
    - schema: authors
      path: content/authors/authors.yml
  form: []
