project:
  status: active
  name: jmolivas/gatsby-theme-novela-example
  buildStatus: ready
  external: false
  provider: github
  deployment:
    packager: npm
    contentDirectory:
      - assets
      - content/authors
      - content/posts
    buildCommand: gatsby build
    builds:
      master:
        branch: master
        weight: 1
        id: _565yqemzi
        environmentVariables: []
    developmentCommand: gatsby develop
    productionBranch: master
    publishDirectory: public
  type: gatsby
schemas:
  - type: content
    definitions:
      schema:
        id: page
        name: Page
      fields:
        - system: false
          widget: text
          name: Title
          type: string
          required: true
          value: ''
          id: title
          orderable: true
          removable: true
        - widget: textarea
          name: Excerpt
          type: string
          required: true
          value: ''
          id: excerpt
          orderable: true
          removable: true
          system: false
        - name: Content
          type: string
          required: true
          value: ''
          id: content
          orderable: true
          removable: true
          system: false
          widget: SlateEditor
        - orderable: true
          removable: true
          system: false
          widget: DatePicker
          name: Date
          type: string
          required: true
          value: ''
          id: date
        - type: string
          required: true
          value: ''
          id: author
          orderable: true
          removable: true
          system: false
          widget: text
          name: Author
        - system: false
          widget: MediaSchema
          name: Hero
          type: string
          required: true
          value: ''
          id: hero
          orderable: true
          removable: true
    schema:
      json:
        properties:
          excerpt:
            default: ''
            type: string
            title: Excerpt
          hero:
            title: Hero
            default: ''
            type: string
          content:
            default: ''
            type: string
            title: Content
          date:
            title: Date
            default: ''
            type: string
          title:
            title: Title
            default: ''
            type: string
          author:
            title: Author
            default: ''
            type: string
        required:
          - title
          - excerpt
          - content
          - date
          - author
          - hero
        type: object
      name: Page
      ui:
        excerpt:
          'ui:widget': textarea
        hero:
          'ui:widget': MediaSchema
        'ui:order':
          - title
          - excerpt
          - content
          - date
          - author
          - hero
          - '*'
        content:
          'ui:widget': SlateEditor
        date:
          'ui:widget': DatePicker
        title:
          'ui:widget': text
        author:
          'ui:widget': text
  - definitions:
      schema:
        id: authors
        name: Authors
      fields:
        - orderable: true
          removable: true
          system: false
          widget: text
          name: Name
          type: string
          required: true
          value: ''
          id: name
        - value: ''
          id: avatar
          orderable: true
          removable: true
          system: false
          widget: MediaSchema
          name: Avatar
          type: string
          required: true
        - removable: true
          system: false
          widget: textarea
          name: Bio
          type: string
          required: true
          value: ''
          id: bio
          orderable: true
        - orderable: true
          removable: true
          system: false
          widget: checkbox
          name: Featured
          type: boolean
          required: false
          value: ''
          id: featured
    schema:
      json:
        required:
          - name
          - avatar
          - bio
        type: object
        properties:
          name:
            title: Name
            default: ''
            type: string
          bio:
            default: ''
            type: string
            title: Bio
          avatar:
            title: Avatar
            default: ''
            type: string
          featured:
            title: Featured
            default: ''
            type: boolean
      name: Authors
      ui:
        'ui:order':
          - name
          - avatar
          - bio
          - featured
          - '*'
        bio:
          'ui:widget': textarea
        avatar:
          'ui:widget': MediaSchema
        featured:
          'ui:widget': checkbox
        name:
          'ui:widget': text
    type: dataset
mapping:
  content:
    - schema: page
      path: content/posts/2017-04-28-understanding-the-gatsby-lifecycle/index.mdx
    - schema: page
      path: content/posts/2018-04-26-how-figma-changed-how-we-design/index.mdx
    - schema: page
      path: content/posts/2017-04-30-how-figma-changed-how-we-design/index.mdx
    - schema: page
      path: content/posts/2017-04-27-building-hoppers-media-centre/index.mdx
    - schema: page
      path: content/posts/2018-04-29-understanding-the-gatsby-lifecycle/index.mdx
    - schema: page
      path: content/posts/2018-04-27-how-figma-changed-how-we-design/index.mdx
    - schema: page
      path: content/posts/2018-04-28-building-hoppers-media-centre/index.mdx
    - schema: page
      path: content/posts/2019-04-26-building-hoppers-media-centre/index.mdx
    - schema: page
      path: content/posts/2019-04-31-understanding-the-gatsby-lifecycle/index.mdx
    - schema: page
      path: content/posts/2018-04-31-building-the-new-hopper-com/index.mdx
    - schema: page
      path: content/posts/2017-04-31-how-figma-changed-how-we-design/index.mdx
    - schema: page
      path: >-
        content/posts/2017-04-30-why-we-built-a-company-before-a-product/index.mdx
    - schema: page
      path: content/posts/2019-04-28-how-figma-changed-how-we-design/index.mdx
    - schema: page
      path: content/posts/2019-04-27-how-figma-changed-how-we-design/index.mdx
    - schema: page
      path: >-
        content/posts/2018-04-30-why-we-built-a-company-before-a-product/index.mdx
    - schema: page
      path: content/posts/2019-04-29-building-the-new-hopper-com/index.mdx
    - schema: page
      path: >-
        content/posts/2019-04-30-why-we-built-a-company-before-a-product/index.mdx
  dataset:
    - schema: authors
      path: content/authors/authors.yml
  form: []
